export const LOGIN_DETAILS = "LOGIN_DETAILS";

export const UNIVERSITIE_DETAILS = "UNIVERSITIE_DETAILS";

export const UNIVERSITIES_START = "UNIVERSITIES_START";

export const UNIVERSITIES_SUCCESS = "UNIVERSITIES_SUCCESS";

export const UNIVERSITIES_FAILURE = "UNIVERSITIES_FAILURE";


